// playbook.js — simple offensive + defensive plays.
// Routes are relative to LOS: dx yards downfield, dz lateral (negative = left sideline in possession's frame).
// The movement layer flips dx sign based on possession direction.

(function (FB) {
  'use strict';

  // --- Route helpers ---
  const R = {
    slant:      [{dx: 2, dz: 0}, {dx: 7, dz: -4}],
    slantRight: [{dx: 2, dz: 0}, {dx: 7, dz: 4}],
    curl10:     [{dx: 10, dz: 0}, {dx: 8, dz: 0}],
    curl12:     [{dx: 12, dz: 0}, {dx: 10, dz: 0}],
    comeback:   [{dx: 14, dz: 0}, {dx: 11, dz: -3}],
    comebackR:  [{dx: 14, dz: 0}, {dx: 11, dz: 3}],
    quickOut:   [{dx: 5, dz: 0}, {dx: 5, dz: -6}],
    quickOutR:  [{dx: 5, dz: 0}, {dx: 5, dz: 6}],
    post:       [{dx: 10, dz: 0}, {dx: 22, dz: -8}],
    postR:      [{dx: 10, dz: 0}, {dx: 22, dz: 8}],
    corner:     [{dx: 10, dz: 0}, {dx: 20, dz: 9}],
    cornerL:    [{dx: 10, dz: 0}, {dx: 20, dz: -9}],
    go:         [{dx: 30, dz: 0}],
    drag:       [{dx: 3, dz: 0}, {dx: 6, dz: 12}],
    dragL:      [{dx: 3, dz: 0}, {dx: 6, dz: -12}],
    flat:       [{dx: 0, dz: 0}, {dx: 3, dz: 8}],
    flatL:      [{dx: 0, dz: 0}, {dx: 3, dz: -8}],
    screen:     [{dx: -3, dz: 5}, {dx: 2, dz: 8}],
    screenL:    [{dx: -3, dz: -5}, {dx: 2, dz: -8}],
    block:      [{dx: -1, dz: 0}],
    wheel:      [{dx: 0, dz: 8}, {dx: 12, dz: 12}],
    wheelL:     [{dx: 0, dz: -8}, {dx: 12, dz: -12}],
    stick:      [{dx: 6, dz: 0}, {dx: 6, dz: 5}],
    stickL:     [{dx: 6, dz: 0}, {dx: 6, dz: -5}],
    inRoute:    [{dx: 10, dz: 0}, {dx: 12, dz: -8}],
    inRouteR:   [{dx: 10, dz: 0}, {dx: 12, dz: 8}],
    outRoute:   [{dx: 10, dz: 0}, {dx: 12, dz: 8}],
    outRouteL:  [{dx: 10, dz: 0}, {dx: 12, dz: -8}],
    dig:        [{dx: 12, dz: 0}, {dx: 14, dz: -10}],
    digR:       [{dx: 12, dz: 0}, {dx: 14, dz: 10}],
    cross:      [{dx: 8, dz: 0}, {dx: 14, dz: 14}],
    crossL:     [{dx: 8, dz: 0}, {dx: 14, dz: -14}],
    fade:       [{dx: 4, dz: 4}, {dx: 20, dz: 10}],
    fadeL:      [{dx: 4, dz: -4}, {dx: 20, dz: -10}],
    hitch:      [{dx: 6, dz: 0}, {dx: 5, dz: 0}],
    checkdown:  [{dx: 2, dz: 2}, {dx: 4, dz: 0}],
  };

  FB.PLAYBOOK = {
    offense: [
      { id: 'inside_zone', name: 'Inside Zone', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 6, dz: 0.5}, {dx: 12, dz: 0}] },
        notes: 'Straight-ahead run between the tackles.' },
      { id: 'power_left', name: 'Power Left', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 4, dz: -3}, {dx: 12, dz: -5}] },
        notes: 'Run behind the left guard.' },
      { id: 'power_right', name: 'Power Right', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 4, dz: 3}, {dx: 12, dz: 5}] },
        notes: 'Run behind the right guard.' },
      { id: 'sweep_left', name: 'Sweep Left', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 2, dz: -10}, {dx: 10, dz: -14}] },
        notes: 'Fast outside run to the left.' },
      { id: 'sweep_right', name: 'Sweep Right', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 2, dz: 10}, {dx: 10, dz: 14}] },
        notes: 'Fast outside run to the right.' },
      { id: 'qb_sneak', name: 'QB Sneak', type: 'run', ballTo: 'QB',
        routes: { }, notes: 'Short yardage — QB dives forward.' },
      { id: 'hb_draw', name: 'HB Draw', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: -2, dz: 0}, {dx: 10, dz: 0}] },
        notes: 'Delayed run, fakes a pass.' },
      { id: 'iris', name: 'Inside Zone (Right)', type: 'run', ballTo: 'RB', gap: 'inside-right',
        routes: { RB: [{dx: 3, dz: 1.5}, {dx: 8, dz: 2.5}, {dx: 14, dz: 3}] },
        notes: 'Inside zone to the right — read the center/right guard double team.' },
      { id: 'illinois', name: 'Inside Zone (Left)', type: 'run', ballTo: 'RB', gap: 'inside-left',
        routes: { RB: [{dx: 3, dz: -1.5}, {dx: 8, dz: -2.5}, {dx: 14, dz: -3}] },
        notes: 'Inside zone to the left — read the center/left guard double team.' },
      { id: 'omar', name: 'Outside Zone (Right)', type: 'run', ballTo: 'RB', gap: 'outside-right',
        routes: { RB: [{dx: 1, dz: 4}, {dx: 5, dz: 9}, {dx: 12, dz: 12}] },
        notes: 'Outside zone to the right — bounce it wide if the edge seals.' },
      { id: 'oklahoma', name: 'Outside Zone (Left)', type: 'run', ballTo: 'RB', gap: 'outside-left',
        routes: { RB: [{dx: 1, dz: -4}, {dx: 5, dz: -9}, {dx: 12, dz: -12}] },
        notes: 'Outside zone to the left — bounce it wide if the edge seals.' },
      { id: 'quick_slants', name: 'Quick Slants', type: 'pass',
        routes: { WR1: R.slant, WR2: R.slantRight, WR3: R.slant, TE: R.stick, RB: R.flatL },
        notes: 'Fast 3-step drop, slants underneath.' },
      { id: 'four_verts', name: 'Four Verticals', type: 'pass',
        routes: { WR1: R.go, WR2: R.go, WR3: R.go, TE: R.go, RB: R.block },
        notes: 'Stretch the defense vertically.' },
      { id: 'curls', name: 'Curl Routes', type: 'pass',
        routes: { WR1: R.curl10, WR2: R.curl12, WR3: R.curl10, TE: R.stick, RB: R.flat },
        notes: 'Receivers hook back at 10–12 yards.' },
      { id: 'smash', name: 'Smash Concept', type: 'pass',
        routes: { WR1: R.corner, WR2: R.quickOut, WR3: R.curl10, TE: R.drag, RB: R.block },
        notes: 'Hi-lo combo — corner/flat.' },
      { id: 'post_corner', name: 'Post–Corner', type: 'pass',
        routes: { WR1: R.post, WR2: R.corner, WR3: R.comeback, TE: R.stick, RB: R.flat },
        notes: 'Deep shot with safety manipulation.' },
      { id: 'flood_right', name: 'Flood Right', type: 'pass',
        routes: { WR1: R.dragL, WR2: R.corner, WR3: R.flat, TE: R.stick, RB: R.wheel },
        notes: 'Three receivers to the right at varied depth.' },
      { id: 'hb_screen', name: 'HB Screen', type: 'pass',
        routes: { WR1: R.go, WR2: R.go, WR3: R.block, TE: R.block, RB: R.screen },
        notes: 'Pass to the RB behind the line.' },
      { id: 'play_action_deep', name: 'Play-Action Deep', type: 'play-action',
        routes: { WR1: R.post, WR2: R.go, WR3: R.comeback, TE: R.drag, RB: R.flat },
        notes: 'Fake the run, throw deep.' },
      { id: 'bootleg_right', name: 'Bootleg Right', type: 'pass',
        routes: { WR1: R.dragL, WR2: R.flat, WR3: R.comeback, TE: R.corner, RB: R.block },
        notes: 'QB rolls right, throws on the move.' },
      { id: 'bootleg_left', name: 'Bootleg Left', type: 'pass',
        routes: { WR1: R.drag, WR2: R.flatL, WR3: R.comebackR, TE: R.cornerL, RB: R.block },
        notes: 'QB rolls left, throws on the move.' },
      { id: 'stretch_right', name: 'Stretch Right', type: 'run', ballTo: 'RB', gap: 'outside-right',
        routes: { RB: [{dx: 0, dz: 6}, {dx: 6, dz: 14}, {dx: 14, dz: 16}] },
        notes: 'Toss sweep — get to the edge fast.' },
      { id: 'stretch_left', name: 'Stretch Left', type: 'run', ballTo: 'RB', gap: 'outside-left',
        routes: { RB: [{dx: 0, dz: -6}, {dx: 6, dz: -14}, {dx: 14, dz: -16}] },
        notes: 'Toss sweep left — get to the edge fast.' },
      { id: 'counter_trey', name: 'Counter Trey', type: 'run', ballTo: 'RB', gap: 'inside-left',
        routes: { RB: [{dx: 1, dz: 2}, {dx: 3, dz: -3}, {dx: 12, dz: -4}] },
        notes: 'Misdirection — fake right, cut back left.' },
      { id: 'mesh', name: 'Mesh', type: 'pass',
        routes: { WR1: R.drag, WR2: R.dragL, WR3: R.curl10, TE: R.stick, RB: R.checkdown },
        notes: 'Crossing routes underneath — pick traffic.' },
      { id: 'double_slant_r', name: 'Double Slants Right', type: 'pass',
        routes: { WR1: R.curl10, WR2: R.slantRight, WR3: R.slantRight, TE: R.block, RB: R.flat },
        notes: 'Two slants on the right side.' },
      { id: 'dagger', name: 'Dagger', type: 'pass',
        routes: { WR1: R.go, WR2: R.dig, WR3: R.curl10, TE: R.drag, RB: R.checkdown },
        notes: 'Seam clears out, dig comes behind it.' },
      { id: 'stick_concept', name: 'Stick Concept', type: 'pass',
        routes: { WR1: R.curl10, WR2: R.quickOutR, WR3: R.hitch, TE: R.stick, RB: R.flat },
        notes: 'Quick stick — high percentage throw.' },
      { id: 'wr_screen_r', name: 'WR Screen Right', type: 'pass',
        routes: { WR1: R.block, WR2: R.screen, WR3: R.go, TE: R.block, RB: R.block },
        notes: 'Quick bubble to the perimeter right.' },
      { id: 'rb_wheel', name: 'RB Wheel', type: 'pass',
        routes: { WR1: R.post, WR2: R.curl10, WR3: R.drag, TE: R.stick, RB: R.wheel },
        notes: 'RB runs a wheel on the sideline.' },

      // --- Additional running plays ---
      { id: 'dive', name: 'HB Dive', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 4, dz: 0}, {dx: 10, dz: 0}] },
        notes: 'Quick A-gap dive — north/south and downhill.' },
      { id: 'iso_run', name: 'ISO (Lead)', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 3, dz: 0.8}, {dx: 9, dz: 1}, {dx: 14, dz: 0.5}] },
        notes: 'Fullback leads through the hole, RB follows.' },
      { id: 'off_tackle_r', name: 'Off-Tackle Right', type: 'run', ballTo: 'RB', gap: 'outside-right',
        routes: { RB: [{dx: 2, dz: 4}, {dx: 8, dz: 6}, {dx: 14, dz: 5}] },
        notes: 'Run between right tackle and TE.' },
      { id: 'off_tackle_l', name: 'Off-Tackle Left', type: 'run', ballTo: 'RB', gap: 'outside-left',
        routes: { RB: [{dx: 2, dz: -4}, {dx: 8, dz: -6}, {dx: 14, dz: -5}] },
        notes: 'Run between left tackle and TE.' },
      { id: 'trap_run', name: 'Trap', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 1, dz: -1}, {dx: 6, dz: 1}, {dx: 12, dz: 0}] },
        notes: 'Backside guard pulls and traps the DT.' },
      { id: 'toss_right', name: 'Toss Right', type: 'run', ballTo: 'RB', gap: 'outside-right',
        routes: { RB: [{dx: -1, dz: 6}, {dx: 4, dz: 12}, {dx: 12, dz: 14}] },
        notes: 'QB pitches; RB runs the edge.' },
      { id: 'toss_left', name: 'Toss Left', type: 'run', ballTo: 'RB', gap: 'outside-left',
        routes: { RB: [{dx: -1, dz: -6}, {dx: 4, dz: -12}, {dx: 12, dz: -14}] },
        notes: 'QB pitches; RB runs the edge.' },
      { id: 'speed_option_r', name: 'Speed Option Right', type: 'run', ballTo: 'QB', gap: 'outside-right',
        routes: { QB: [{dx: 1, dz: 4}, {dx: 5, dz: 9}, {dx: 11, dz: 11}],
                  RB: [{dx: 1, dz: 8}, {dx: 7, dz: 14}] },
        notes: 'QB attacks the edge — pitch or keep.' },
      { id: 'speed_option_l', name: 'Speed Option Left', type: 'run', ballTo: 'QB', gap: 'outside-left',
        routes: { QB: [{dx: 1, dz: -4}, {dx: 5, dz: -9}, {dx: 11, dz: -11}],
                  RB: [{dx: 1, dz: -8}, {dx: 7, dz: -14}] },
        notes: 'QB attacks the edge — pitch or keep.' },
      { id: 'read_option', name: 'Zone Read', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 2, dz: -2}, {dx: 8, dz: -1}, {dx: 14, dz: 0}],
                  QB: [{dx: 1, dz: 2}, {dx: 6, dz: 5}] },
        notes: 'QB reads the backside DE — keep or hand off.' },
      { id: 'qb_power', name: 'QB Power', type: 'run', ballTo: 'QB',
        routes: { QB: [{dx: 3, dz: 1}, {dx: 9, dz: 2}, {dx: 14, dz: 1}] },
        notes: 'Designed QB run with a pulling guard.' },
      { id: 'jet_sweep_r', name: 'Jet Sweep Right', type: 'run', ballTo: 'WR3', gap: 'outside-right',
        routes: { WR3: [{dx: 0, dz: 4}, {dx: 5, dz: 14}, {dx: 12, dz: 16}],
                  RB: [{dx: 2, dz: -2}, {dx: 6, dz: -2}] },
        notes: 'Jet motion across the formation, ball to slot.' },
      { id: 'jet_sweep_l', name: 'Jet Sweep Left', type: 'run', ballTo: 'WR3', gap: 'outside-left',
        routes: { WR3: [{dx: 0, dz: -4}, {dx: 5, dz: -14}, {dx: 12, dz: -16}],
                  RB: [{dx: 2, dz: 2}, {dx: 6, dz: 2}] },
        notes: 'Jet motion across the formation, ball to slot.' },
      { id: 'wildcat_run', name: 'Wildcat', type: 'run', ballTo: 'RB',
        routes: { RB: [{dx: 4, dz: 1}, {dx: 10, dz: 3}, {dx: 16, dz: 4}] },
        notes: 'Direct snap to RB — power run with a lead blocker.' },

      // --- Additional passing plays / concepts ---
      { id: 'go_route', name: 'Go Routes', type: 'pass',
        routes: { WR1: R.go, WR2: R.go, WR3: R.curl10, TE: R.stick, RB: R.checkdown },
        notes: 'Send the outside two deep — clear out underneath.' },
      { id: 'seam_te', name: 'TE Seam', type: 'pass',
        routes: { WR1: R.comeback, WR2: R.comebackR, WR3: R.curl10, TE: R.go, RB: R.flat },
        notes: 'Tight end attacks the seam.' },
      { id: 'levels', name: 'Levels', type: 'pass',
        routes: { WR1: R.dig, WR2: R.inRouteR, WR3: R.curl10, TE: R.drag, RB: R.checkdown },
        notes: 'Two in-cuts at different depths — high/low the LBs.' },
      { id: 'high_low_r', name: 'High–Low Right', type: 'pass',
        routes: { WR1: R.curl10, WR2: R.dig, WR3: R.flat, TE: R.stick, RB: R.checkdown },
        notes: 'Dig over a flat route — hi/lo the curl-flat defender.' },
      { id: 'ladder', name: 'Ladder', type: 'pass',
        routes: { WR1: R.flat, WR2: R.curl10, WR3: R.dig, TE: R.go, RB: R.checkdown },
        notes: 'Stacked routes at 3, 10, and 14 yards on one side.' },
      { id: 'tunnel_screen', name: 'Tunnel Screen', type: 'pass',
        routes: { WR1: [{dx: -2, dz: 2}, {dx: 4, dz: 6}], WR2: R.go, WR3: R.block, TE: R.block, RB: R.block },
        notes: 'WR steps back inside; linemen release downfield.' },
      { id: 'bubble_screen_r', name: 'Bubble Screen Right', type: 'pass',
        routes: { WR1: R.go, WR2: [{dx: -1, dz: 8}, {dx: 3, dz: 14}], WR3: R.block, TE: R.block, RB: R.block },
        notes: 'Quick out-and-up bubble to the right slot.' },
      { id: 'bubble_screen_l', name: 'Bubble Screen Left', type: 'pass',
        routes: { WR1: [{dx: -1, dz: -8}, {dx: 3, dz: -14}], WR2: R.go, WR3: R.block, TE: R.block, RB: R.block },
        notes: 'Quick out-and-up bubble to the left slot.' },
      { id: 'middle_screen', name: 'Middle Screen', type: 'pass',
        routes: { WR1: R.go, WR2: R.go, WR3: R.curl10, TE: [{dx: -2, dz: 0}, {dx: 4, dz: 0}], RB: R.flat },
        notes: 'TE delays then catches a middle screen.' },
      { id: 'play_action_post', name: 'Play-Action Post', type: 'play-action',
        routes: { WR1: R.post, WR2: R.comebackR, WR3: R.drag, TE: R.flat, RB: R.block },
        notes: 'Sell the run, take the post off it.' },
      { id: 'naked_boot_r', name: 'Naked Bootleg Right', type: 'pass',
        routes: { WR1: R.dragL, WR2: R.flat, WR3: R.comeback, TE: R.cornerL, RB: R.flat },
        notes: 'No protection — QB rolls right and reads on the move.' },
      { id: 'sprint_out_r', name: 'Sprint Out Right', type: 'pass',
        routes: { WR1: R.comeback, WR2: R.flat, WR3: R.curl10, TE: R.corner, RB: R.block },
        notes: 'QB sprints right; flat/comeback combo.' },
      { id: 'sprint_out_l', name: 'Sprint Out Left', type: 'pass',
        routes: { WR1: R.flatL, WR2: R.comebackR, WR3: R.curl10, TE: R.cornerL, RB: R.block },
        notes: 'QB sprints left; flat/comeback combo.' },
      { id: 'flea_flicker', name: 'Flea Flicker', type: 'play-action',
        routes: { WR1: R.go, WR2: R.post, WR3: R.comeback, TE: R.stick,
                  RB: [{dx: 3, dz: 0}, {dx: 1, dz: 0}, {dx: -3, dz: 0}] },
        notes: 'Fake handoff, RB pitches back, throw deep.' },
      { id: 'hb_pass', name: 'Halfback Pass', type: 'play-action',
        routes: { WR1: R.go, WR2: R.post, WR3: R.flat,
                  TE: R.drag, RB: [{dx: 2, dz: 5}, {dx: 0, dz: 6}] },
        notes: 'RB takes the toss then throws — trick play.' },
      { id: 'rpo_slant', name: 'RPO — Slant', type: 'pass',
        routes: { WR1: R.slant, WR2: R.curl10, WR3: R.flat, TE: R.block,
                  RB: [{dx: 4, dz: 0}, {dx: 8, dz: 0}] },
        notes: 'Run-pass option: hand off, or pull and throw the slant.' },
      { id: 'hail_mary', name: 'Hail Mary', type: 'pass',
        routes: { WR1: R.go, WR2: R.go, WR3: R.go, TE: R.go, RB: R.checkdown },
        notes: 'End-of-half heave — everybody to the end zone.' },
    ],
    defense: [
      { id: 'base_cover2', name: '4-3 Cover 2', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 8, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -10 },
          SLB: { type: 'zone', depth: 4, lateral: 10 },
          LCB: { type: 'zone', depth: 4, lateral: -18 },
          RCB: { type: 'zone', depth: 4, lateral: 18 },
          FS: { type: 'zone', depth: 16, lateral: -10 },
          SS: { type: 'zone', depth: 16, lateral: 10 },
        }, notes: 'Safeties split halves deep. Good against deep passes.' },
      { id: 'base_cover3', name: '4-3 Cover 3', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 7, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -12 },
          SLB: { type: 'zone', depth: 4, lateral: 12 },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 14, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 8, lateral: 6 },
        }, notes: 'Three deep, four underneath.' },
      { id: 'cover1_man', name: 'Cover 1 Man', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'man', target: 'RB' },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'zone', depth: 4, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'man', target: 'WR3' },
        }, notes: 'Man-to-man with a single deep safety.' },
      { id: 'cover0_blitz', name: 'Cover 0 Blitz', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' }, WLB: { type: 'blitz' }, SLB: { type: 'blitz' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'man', target: 'WR3' },
          SS: { type: 'man', target: 'TE' },
        }, notes: 'All-out pressure, no safety help.' },
      { id: 'nickel_cover2', name: 'Nickel Cover 2', formation: 'nickel',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 8, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'man', target: 'WR3' },
          LCB: { type: 'zone', depth: 5, lateral: -18 },
          RCB: { type: 'zone', depth: 5, lateral: 18 },
          FS: { type: 'zone', depth: 16, lateral: -10 },
          SS: { type: 'zone', depth: 16, lateral: 10 },
        }, notes: 'Five DBs on passing downs.' },
      { id: 'mlb_blitz', name: 'MLB Blitz', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'man', target: 'TE' },
        }, notes: 'Mike blitz up the A-gap.' },
      { id: 'olb_blitz_weak', name: 'OLB Blitz Weak', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          WLB: { type: 'blitz' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'zone', depth: 6, lateral: -18 },
          RCB: { type: 'zone', depth: 6, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 10, lateral: 6 },
        }, notes: 'Weak-side pressure.' },
      { id: 'olb_blitz_strong', name: 'OLB Blitz Strong', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          SLB: { type: 'blitz' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          LCB: { type: 'zone', depth: 6, lateral: -18 },
          RCB: { type: 'zone', depth: 6, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 10, lateral: 6 },
        }, notes: 'Strong-side pressure.' },
      { id: 'safety_blitz', name: 'Safety Blitz', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          SS: { type: 'blitz' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
        }, notes: 'Strong safety comes on the blitz.' },
      { id: 'cover4', name: 'Cover 4 Quarters', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -10 },
          SLB: { type: 'zone', depth: 4, lateral: 10 },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 14, lateral: 18 },
          FS: { type: 'zone', depth: 16, lateral: -6 },
          SS: { type: 'zone', depth: 16, lateral: 6 },
        }, notes: 'Four deep — no long touchdowns.' },
      { id: 'prevent', name: 'Prevent Defense', formation: 'dime',
        assignments: {
          LE: { type: 'rush' }, RE: { type: 'rush' },
          DT: { type: 'zone', depth: 5, lateral: -3 }, NT: { type: 'zone', depth: 5, lateral: 3 },
          MLB: { type: 'zone', depth: 10, lateral: 0 },
          WLB: { type: 'zone', depth: 10, lateral: -10 },
          SLB: { type: 'zone', depth: 10, lateral: 10 },
          LCB: { type: 'zone', depth: 22, lateral: -18 },
          RCB: { type: 'zone', depth: 22, lateral: 18 },
          FS: { type: 'zone', depth: 25, lateral: -8 },
          SS: { type: 'zone', depth: 25, lateral: 8 },
        }, notes: 'Keep everything in front — end-of-half.' },
      { id: 'goal_line', name: 'Goal Line', formation: 'goal-line',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'rush' },
          WLB: { type: 'zone', depth: 2, lateral: -6 },
          SLB: { type: 'zone', depth: 2, lateral: 6 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 4, lateral: 0 },
          SS: { type: 'man', target: 'TE' },
        }, notes: 'Stack the box near the goal line.' },
      { id: 'zone_blitz', name: 'Zone Blitz', formation: '4-3',
        assignments: {
          LE: { type: 'zone', depth: 4, lateral: -8 },
          DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'zone', depth: 6, lateral: -8 },
          SLB: { type: 'zone', depth: 6, lateral: 8 },
          LCB: { type: 'zone', depth: 12, lateral: -18 },
          RCB: { type: 'zone', depth: 12, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 10, lateral: 6 },
        }, notes: 'Drop a lineman, blitz a linebacker.' },
      { id: 'dime_man', name: 'Dime Coverage', formation: 'dime',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'man', target: 'RB' },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'zone', depth: 6, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'man', target: 'WR3' },
        }, notes: 'Six DBs — obvious passing downs.' },
      { id: 'cover2_man', name: 'Cover 2 Man', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'man', target: 'RB' },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'zone', depth: 4, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 16, lateral: -10 },
          SS: { type: 'zone', depth: 16, lateral: 10 },
        }, notes: 'Man under, two-deep safeties.' },
      { id: 'nickel_cover3', name: 'Nickel Cover 3', formation: 'nickel',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'man', target: 'WR3' },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 14, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 8, lateral: 4 },
        }, notes: 'Three deep with the nickel package.' },
      { id: 'nickel_cover4', name: 'Nickel Quarters', formation: 'nickel',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -8 },
          SLB: { type: 'man', target: 'WR3' },
          LCB: { type: 'zone', depth: 12, lateral: -18 },
          RCB: { type: 'zone', depth: 12, lateral: 18 },
          FS: { type: 'zone', depth: 15, lateral: -6 },
          SS: { type: 'zone', depth: 15, lateral: 6 },
        }, notes: 'Four deep with a slot defender.' },
      { id: 'nickel_blitz', name: 'Nickel Blitz', formation: 'nickel',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'blitz' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'man', target: 'WR3' },
        }, notes: 'Nickel with Mike and slot on a blitz.' },
      { id: 'dime_cover3', name: 'Dime Cover 3', formation: 'dime',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 14, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 10, lateral: 4 },
        }, notes: 'Six DBs, three deep — max pass coverage.' },
      { id: 'fire_zone', name: 'Fire Zone Blitz', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'zone', depth: 4, lateral: 6 }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'zone', depth: 6, lateral: -10 },
          SLB: { type: 'blitz' },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 14, lateral: 18 },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'zone', depth: 8, lateral: 4 },
        }, notes: '5-man rush with 3-deep 3-under.' },
      { id: 'bear_front', name: '46 Bear Front', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'rush' },
          WLB: { type: 'rush' },
          SLB: { type: 'zone', depth: 4, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 14, lateral: 0 },
          SS: { type: 'man', target: 'TE' },
        }, notes: '8-man box — stuff the run.' },
      { id: 'double_a_blitz', name: 'Double A-Gap', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'blitz' },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'man', target: 'TE' },
        }, notes: 'Two LBs blitz the A-gaps.' },
      { id: 'cb_blitz_right', name: 'CB Blitz Right', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'blitz' },
          FS: { type: 'zone', depth: 16, lateral: -4 },
          SS: { type: 'man', target: 'WR2' },
        }, notes: 'Corner comes off the edge right.' },
      { id: 'cb_blitz_left', name: 'CB Blitz Left', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'blitz' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 16, lateral: 4 },
          SS: { type: 'man', target: 'WR1' },
        }, notes: 'Corner comes off the edge left.' },
      { id: 'robber', name: 'Robber Coverage', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'man', target: 'RB' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 20, lateral: 0 },
          SS: { type: 'zone', depth: 10, lateral: 0 },
        }, notes: 'Safety robs the intermediate middle.' },
      { id: 'quarters_press', name: 'Press Quarters', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 5, lateral: 0 },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'man', target: 'RB' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 15, lateral: -6 },
          SS: { type: 'zone', depth: 15, lateral: 6 },
        }, notes: 'Press corners with quarters behind.' },
      { id: 'cover6', name: 'Cover 6', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -10 },
          SLB: { type: 'zone', depth: 4, lateral: 10 },
          LCB: { type: 'zone', depth: 14, lateral: -18 },
          RCB: { type: 'zone', depth: 8, lateral: 18 },
          FS: { type: 'zone', depth: 16, lateral: -6 },
          SS: { type: 'zone', depth: 14, lateral: 14 },
        }, notes: 'Quarter-quarter-half split coverage.' },
      { id: 'overload_right', name: 'Overload Right', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'blitz' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 18, lateral: 0 },
          SS: { type: 'blitz' },
        }, notes: 'Triple-A overload from the right.' },
      { id: 'overload_left', name: 'Overload Left', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'blitz' },
          WLB: { type: 'blitz' },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'blitz' },
          SS: { type: 'zone', depth: 14, lateral: 6 },
        }, notes: 'Triple overload from the left.' },
      { id: 'engage_eight', name: 'Engage 8 (Run Stop)', formation: 'goal-line',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'rush' },
          WLB: { type: 'rush' },
          SLB: { type: 'rush' },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 6, lateral: 0 },
          SS: { type: 'rush' },
        }, notes: 'All-out run stop — sell out on short yardage.' },
      { id: 'three_four_base', name: '3-4 Base', formation: '3-4',
        assignments: {
          LE: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          DT: { type: 'blitz' },
          MLB: { type: 'zone', depth: 6, lateral: 0 },
          WLB: { type: 'zone', depth: 5, lateral: -8 },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 16, lateral: -6 },
          SS: { type: 'zone', depth: 16, lateral: 6 },
        }, notes: '3 down linemen, 4 LBs — flexible front.' },
      { id: 'four_four_run', name: '4-4 Run Stop', formation: '4-4',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 4, lateral: 0 },
          WLB: { type: 'zone', depth: 4, lateral: -8 },
          SLB: { type: 'zone', depth: 4, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 12, lateral: 0 },
          SS: { type: 'zone', depth: 4, lateral: 4 },
        }, notes: '8 in the box with cover-3 over the top.' },
      { id: 'two_minute_d', name: 'Two-Minute Defense', formation: 'dime',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'zone', depth: 8, lateral: 0 },
          WLB: { type: 'zone', depth: 8, lateral: -10 },
          SLB: { type: 'zone', depth: 8, lateral: 10 },
          LCB: { type: 'zone', depth: 16, lateral: -18 },
          RCB: { type: 'zone', depth: 16, lateral: 18 },
          FS: { type: 'zone', depth: 22, lateral: -8 },
          SS: { type: 'zone', depth: 22, lateral: 8 },
        }, notes: 'Keep the ball in front, force checkdowns and burn clock.' },
      { id: 'match_quarters', name: 'Match Quarters', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'man', target: 'TE' },
          WLB: { type: 'man', target: 'RB' },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 14, lateral: -6 },
          SS: { type: 'zone', depth: 14, lateral: 6 },
        }, notes: 'Pattern-match: zone unless the receiver goes vertical.' },
      { id: 'free_safety_help', name: 'Free Safety Help', formation: '4-3',
        assignments: {
          LE: { type: 'rush' }, DT: { type: 'rush' }, NT: { type: 'rush' }, RE: { type: 'rush' },
          MLB: { type: 'man', target: 'RB' },
          WLB: { type: 'man', target: 'TE' },
          SLB: { type: 'zone', depth: 5, lateral: 8 },
          LCB: { type: 'man', target: 'WR1' },
          RCB: { type: 'man', target: 'WR2' },
          FS: { type: 'zone', depth: 20, lateral: 0 },
          SS: { type: 'man', target: 'WR3' },
        }, notes: 'Single-high free safety roams the deep middle.' },
    ],
  };

  // Pick a random AI play of the given side (for the non-user team).
  FB.pickAIPlay = function (side) {
    return FB.pickAIPlayAdaptive ? FB.pickAIPlayAdaptive(side) : FB.PLAYBOOK[side][0];
  };

  // Adaptive picker that reads FB.state.userTendencies to counter the human.
  // Defense against a pass-heavy user tilts toward zone/dime/prevent; against run, toward base/goal-line/blitz.
  // Offense against a user who blitzes a lot tilts toward screens/quick passes; against zone, toward verticals.
  // Difficulty tiers tighten the AI's pick:
  //   - freshman: top-6, heavy randomness
  //   - jv: top-4
  //   - varsity: top-3
  //   - all-state: top-2, also boosts harder concepts (blitzes, man coverage)
  FB.pickAIPlayAdaptive = function (side) {
    const list = FB.PLAYBOOK[side];
    const t = (FB.state && FB.state.userTendencies) || { run: 0, pass: 0, left: 0, right: 0, blitz: 0, zone: 0 };
    const totalOff = Math.max(1, (t.run || 0) + (t.pass || 0));
    const runBias = (t.run || 0) / totalOff;   // 0..1
    const passBias = (t.pass || 0) / totalOff; // 0..1
    const leftBias = ((t.left || 0) - (t.right || 0)) / Math.max(1, (t.left || 0) + (t.right || 0));
    const blitzBias = ((t.blitz || 0) - (t.zone || 0)) / Math.max(1, (t.blitz || 0) + (t.zone || 0));

    const diff = (FB.state && FB.state.difficulty) || 'varsity';
    const diffTable = {
      freshman:  { top: 6, noise: 1.0, hardBoost: -0.3 },
      jv:        { top: 4, noise: 0.7, hardBoost: 0.0 },
      varsity:   { top: 3, noise: 0.5, hardBoost: 0.3 },
      'all-state':{ top: 2, noise: 0.25, hardBoost: 0.8 },
    };
    const cfg = diffTable[diff] || diffTable.varsity;

    const scored = list.map((p) => {
      let s = Math.random() * cfg.noise; // base randomness scales with difficulty
      if (side === 'defense') {
        const isRunStopper = /goal|blitz/i.test(p.name) || /mlb_blitz|safety_blitz|goal_line/.test(p.id);
        const isPassDef = /nickel|dime|cover2|cover3|cover4|prevent|zone_blitz/i.test(p.id);
        const isHardD = /blitz|cover0|cover1|press|man/i.test(p.id) || /blitz|press/i.test(p.name);
        if (isRunStopper) s += runBias * 1.6;
        if (isPassDef) s += passBias * 1.6;
        // Harder difficulty favors tougher defenses (blitzes, tight man, etc.)
        if (isHardD) s += cfg.hardBoost;
        // If user favored a side on runs, prefer blitzes to that side.
        if (/strong/i.test(p.id) && leftBias < -0.2) s += 0.5;
        if (/weak/i.test(p.id) && leftBias > 0.2) s += 0.5;
      } else {
        const deep = /four_verts|post_corner|play_action_deep/.test(p.id);
        const quick = /slants|screen|curls|bootleg/.test(p.id);
        const run = p.type === 'run';
        if (blitzBias > 0.2) s += quick ? 0.9 : (deep ? 0.4 : 0);
        if (blitzBias < -0.2) s += deep ? 0.7 : 0;
        if (blitzBias < 0) s += run ? 0.4 : 0; // if user sits back, AI runs
      }
      return { p, s };
    });
    scored.sort((a, b) => b.s - a.s);
    const top = scored.slice(0, Math.min(cfg.top, scored.length));
    return top[Math.floor(Math.random() * top.length)].p;
  };

  // Call when the user confirms a play so the AI can learn.
  FB.recordUserPlay = function (side, play) {
    if (!FB.state) return;
    const t = FB.state.userTendencies = FB.state.userTendencies
      || { run: 0, pass: 0, left: 0, right: 0, blitz: 0, zone: 0, recentPlays: [] };
    if (side === 'offense') {
      if (play.type === 'run') t.run++;
      else t.pass++;
      if (/left|weak/i.test(play.id) || play.gap === 'inside-left' || play.gap === 'outside-left') t.left++;
      if (/right|strong/i.test(play.id) || play.gap === 'inside-right' || play.gap === 'outside-right') t.right++;
    } else {
      if (/blitz|cover0|cover1|goal/i.test(play.id)) t.blitz++;
      else t.zone++;
    }
    t.recentPlays.push(play.id);
    if (t.recentPlays.length > 8) t.recentPlays.shift();
  };

  // Resolve a slot's relative point on the field.
  FB.zoneTargetFor = function (assignment, losX, dir, fieldWidSign) {
    const dx = assignment.depth * dir;
    const dz = assignment.lateral * (fieldWidSign || 1);
    return new THREE.Vector3(losX + dx, 0, dz);
  };

  // Expand a route (dx/dz waypoints) into absolute field waypoints for an entity.
  FB.expandRoute = function (waypoints, startPos, dir) {
    if (!waypoints || !waypoints.length) return [];
    return waypoints.map(w => new THREE.Vector3(startPos.x + w.dx * dir, 0, startPos.z + w.dz));
  };

})(window.FB);
